version: "1"
services:
  react-app:
    build: ./web_app
    ports: 
      - "8080:8080"
    networks:
      - mern-app
  api-server:
    build: ./backend
    ports: 
      - "8000:8000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge

