version: "1"
services:
  react-app:
    build: ./web_app
    ports: 
      - "8080:8080"
    networks:
      - mern-app
  api-server:
    build: ./app
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
