version: "1"
services:
  react-app:
    build: ./web_app
    ports: 
      - "5173:5173"
    networks:
      - mern-app
  api-server:
    build: ./app
    ports: 
      - "3000:3000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge

